name: Update ZTC CSV

on:
  schedule:
    - cron: '0 5 * * *'  # daily at 05:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          START_URL: https://www.laccd.edu/students/class-search
        run: |
          python fetch_ztc.py

      - name: Commit updated CSV
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ztc_live.csv
          git commit -m "Auto-update ZTC CSV" || echo "No changes to commit"
          git push
